DT-HYUNJUN/movies-review-site

- config/settings.py
> [ADD] test

- accounts/admin.py
- accounts/forms.py
- accounts/templates/accounts/signup.html
- accounts/urls.py
- accounts/views.py
- 로그인
- 회원가입
- 로그아웃 
views.py 작성
> [ADD]accounts:로그인/회원가입/로그아웃

- movies/templates/movies/detail.html
- movies/urls.py
- movies/views.py
- Create movies index url & view
- Create movies detail url & view
> [ADD] index, detail url & view

- accounts/forms.py
- accounts/models.py
- accounts/urls.py
- accounts/views.py
- 프로필 정보(유저만 넘김)
- 프로필 수정
- 비밀번호 변경
- 로그인 유지시킴.
- 유저 탈퇴
- 팔로우 / 팔로우 취소
- User 모델 컬럼변경 및 주석 추가
- followers -> followings
- 로그인 여부 확인 부분
- 함수 뷰: login_required 활용
- 클래스 뷰: LoginRequiredMixin 활용
- 클래스 뷰로 전환
> [ADD]accounts:프로필, 정보수정, 탈퇴, 팔로우

- static/style/index.css
- templates/header.html
navbar position 수정
carousel 상하 shadow 추가
> [ADD]index-shadow

- movies/templates/movies/detail.html
- movies/urls.py
- movies/views.py
Add crew and cast information to movies/detail.
> [ADD] crew and cast list

- accounts/forms.py
- accounts/templates/accounts/login.html
- static/style/accounts/account.css
- static/style/movies/index.css
> [ADD] accounts signup templates

- static/style/accounts/account.css
- static/style/base.css
- static/style/footer.css
- templates/base.html
- templates/footer.html
> [FIX] footer fix

- static/style/base.css
- static/style/footer.css
- templates/footer.html
> [UPDATE]footer

- movies/templates/movies/person_detail.html
- movies/views.py
Create view, template for the person information.
> [ADD] person_detail view, template

- movies/templates/movies/index.html
> [ADD] index

- config/settings.py
- movies/templates/movies/carousel.html
- movies/templates/movies/detail.html
- movies/templates/movies/person_detail.html
- reviews/forms.py
- reviews/views.py
- static/js/navbar.js
- static/js/reviews/create.js
- static/style/accounts/account.css
- static/style/base.css
- static/style/footer.css
- static/style/header.css
- static/style/movies/detail.css
- static/style/movies/person_detail.css
- templates/base.html
- templates/footer.html
- templates/header.html
- utils/context_processors.py
> [UPDATE] reviews create modal templates

- movies/templates/movies/detail.html
- static/style/reviews/create.css
- templates/base.html
- movies detail - 리뷰 작성 모달의 스포일러 버튼 툴팁 추가
> Movies detail review

- movies/templates/movies/detail.html
- movies/templates/movies/person_detail.html
- static/style/movies/detail.css
- static/style/movies/person_detail.css
person-detail 이미지 작성
detail 수정
> [ADD] person-detail-image

- movies/templates/movies/detail.html
- static/style/movies/detail.css
- [reviews] review create modal 비 로그인 시 리뷰 작성 폼이 나오던 것을 로그인/회원가입 안내창 모달 출력
> [UPDATE] reviews create modal

- movies/templates/movies/search.html
- static/style/accounts/account.css
- static/style/movies/search.css
- templates/base.html
> [UPDATE] search template

- movies/templates/movies/detail.html
- movies/templates/movies/person_detail.html
- movies/views.py
- [movies] detail 페이지에 유튜브 메인 예고편 추가
- (params에 language: ko-kr로 해서 한국어 예고편을 출력하려 했으나, 한국어 버전이 없는 경우가 많아, 영어 예고편으로 출력)
- [movies] detail 페이지에서 감독/배우 이름을 한국어로 변경, 
- 한국어 이름이 없는 경우, 영어 이름으로 출력
> [ADD] movies detail trailer video / [UPDATE] movies detail kor_name

- movies/templates/movies/detail.html
- movies/templates/movies/index.html
- movies/views.py
- static/js/video.js
- static/style/movies/detail.css
- static/style/movies/index.css
- [movies] 기존 index carousel의 내용을 상영 중인 영화로 변경
> [UPDATE] movies index carousel

- movies/templates/movies/detail.html
- [reviews] movies detail 페이지에서 리뷰 작성자 프로필 이미지 분기문 추가
> [FIX] movies detail review profile_image

- accounts/templates/accounts/change_password.html
- accounts/templates/accounts/login.html
- accounts/templates/accounts/signup.html
- accounts/templates/accounts/update.html
- movies/templates/movies/search.html
- static/style/accounts/account.css
- static/style/base.css
- static/style/footer.css
- static/style/movies/index.css
- static/style/movies/search.css
페이지 base 이미지 작성
search template 작성
> [ADD] search

- movies/templates/movies/detail.html
- movies/views.py
- static/js/movies/rating-chart.js
- static/style/movies/detail.css
- [movies] rating-chart에 데이터 연동
- [reviews] 0점은 입력 불가였던 부분(rating input의 value값이 없었음)을 기본값 0으로 변경
> [UPDATE] movies detail rating-chart

- movies/templates/movies/detail.html
- movies/views.py
- static/js/movies/spoiler.js
- static/style/base/base.css
- [movies] detail 페이지 리뷰 항목에 스포일러 버튼 추가
- [reviews] 별점 평균값을 구하는 부분에서, 리뷰가 없는 경우의 divisionByZero  FIX
> [ADD] movies detail reviews spoiler system

- movies/templates/movies/detail.html
- movies/templates/movies/index.html
- movies/views.py
- static/js/movies/rating-chart.js
- static/style/movies/detail.css
- [movies] index 페이지에서 각 영화의 평균 별점 출력
- 리뷰가 하나도 없을 시 출력 X -> 0으로 출력하면 오해가 있을 거라 판단
> [ADD] movies index avg_rating

- accounts/forms.py
- movies/templates/movies/collection_detail.html
- movies/templates/movies/detail.html
- movies/views.py
- static/style/base/header.css
- static/style/movies/collection_detail.css
- static/style/movies/detail.css
- templates/style.html
- [navbar] search bar text color fix -> white
> [UPDATE] navbar search

- accounts/templates/accounts/profile.html
- accounts/views.py
- static/style/accounts/profile.css
- [accounts] profile.html nickname position fix
> [UPDATE] accounts profile templates

- movies/templates/movies/detail.html
- movies/views.py
- [movies] detail rating-chart dictionary fix
> [FIX] movies detail rating-chart

- movies/templates/movies/person_detail.html
- static/style/movies/person_detail.css
> [ADD] person-detail template

- movies/templates/movies/person_detail.html
- static/style/movies/person_detail.css
- templates/footer.html
> [FIX] person-detail fix

- accounts/templates/accounts/profile.html
- movies/templates/movies/carousel.html
- movies/templates/movies/detail.html
- movies/templates/movies/index.html
- movies/views.py
- static/img/rating-star.svg
- static/js/movies/carousel.js
- static/js/reviews/index.js
- static/style/accounts/profile.css
- static/style/movies/index.css
> [UPDATE] movies detail carousel

- movies/forms.py
- movies/templates/movies/collection_detail.html
- movies/templates/movies/create.html
- static/js/movies/create_collection.js
- static/style/base/header.css
- static/style/movies/collection.css
- static/style/movies/collection_detail.css
- static/style/movies/index.css
- templates/header.html
- [movies] collcetions detail templates
- [movies] collcetions create templates
> [UPDATE] movies collections detail templates

- accounts/forms.py
- config/settings.py
- movies/templates/movies/create.html
- movies/templates/movies/detail.html
- movies/templates/movies/genre_movies.html
- movies/views.py
- static/js/movies/create_collection.js
- static/style/base/header.css
- static/style/movies/detail.css
- static/style/movies/genre.css
- templates/header.html
- utils/context_processors.py
> [ADD] genre serach modal

- movies/templates/movies/collection_detail.html
- movies/urls.py
- movies/views.py
> [ADD]컬렉션 좋아요 기능 작성

- accounts/templates/accounts/profile.html
- static/style/accounts/profile.css
- [accounts] profile collections poster group update
> [UPDATE] profile collections poster group

- accounts/templates/accounts/profile.html
- config/settings.py
- movies/templates/movies/genre_movies.html
- movies/templates/movies/index.html
- static/style/accounts/profile.css
- static/style/movies/genre.css
프로필 수정
intcomma 적용
장르 select 추가
> [ADD] profile

- movies/templates/movies/detail.html
- movies/templates/movies/search.html
- movies/views.py
- [movies] detail production country fix -> blan when empty
> [FIX] movies detail production country

- accounts/templates/accounts/profile.html
- static/style/accounts/profile.css
- [accounts] profile like_movies templates
> [ADD] profile like_movies

- movies/templates/movies/genre_movies.html
- static/js/movies/genre.js
- static/style/base/header.css
- static/style/movies/genre.css
- 검색어 추천, 장르 정렬 필터링 select태그 색상 변경
- select태그에서 선택된 옵션이 유지되도록 수정
> [Fix] 검색어 추천과 필터링 옵션 색상 변경, 선택된 필터가 고정되어 보이도록 기능 추가

- movies/templates/movies/detail.html
- movies/views.py
- static/style/movies/detail.css
> [ADD] detail recommend

- accounts/templates/accounts/profile.html
- movies/templates/movies/detail.html
- movies/templates/movies/index.html
- movies/views.py
- static/js/movies/carousel.js
- static/js/movies/video.js
- static/js/reviews/index.js
- static/style/accounts/profile.css
- static/style/movies/detail.css
- static/style/movies/index.css
- templates/header.html
- [movies] collection templates
- [movies] video modal
> [UPDATE] collections

- movies/templates/movies/update.html
- static/js/movies/update_collection_copy.js
- static/style/movies/collection.css
- modify CollectionMovieDeleteForm output in update collection template
> [UPDATE] collection update template

- movies/views.py
- requirements.txt
- 인덱스 view에 키워드 관련 내용 추가했습니다! 주석처리 되어 있음.
> [ADD]인덱스 view: 태그추가(주석처리함)

- movies/views.py
- [movies] detail no-login fix
> [FIX] movies detail no-login

- movies/templates/movies/detail.html
- movies/views.py
- static/style/movies/detail.css
> [ADD] movies detail keywords

- movies/templates/movies/update.html
- movies/views.py
- static/js/movies/update_collection_copy.js
- send movie poster path to JS through dataset
- update poster image print way
> [FIX] movie poster bug
